# Generated by Django 4.2.5 on 2023-11-02 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_userprofile_about_me'),
        ('travel', '0002_TravelAim_Migrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('travel_date', models.DateTimeField()),
                ('days', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=2500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('INITIATED', 'INITIATED'), ('COMPLETED', 'COMPLETED'), ('CANCELED', 'CANCELED'), ('PENDING', 'PENDING')], max_length=11, null=True)),
                ('intrested_users', models.ManyToManyField(blank=True, related_name='Interested_user', to='accounts.userprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
