# Generated by Django 4.2.5 on 2023-11-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_travelplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='status',
            field=models.CharField(blank=True, choices=[('INITIATED', 'INITIATED'), ('COMPLETED', 'COMPLETED'), ('CANCELED', 'CANCELED'), ('PENDING', 'PENDING')], default='INITIATED', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='travel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
