# Generated by Django 4.2.5 on 2023-11-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_travelplan_status_alter_travelplan_travel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplan',
            name='intrested_users',
        ),
    ]
