# Generated by Django 4.2.5 on 2023-11-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_userprofile_about_me'),
        ('travel', '0007_travelrequests_created_at_travelrequests_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TravelRequests',
            new_name='TravelRequest',
        ),
    ]
