# Generated by Django 4.2.5 on 2023-11-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_mytrip_alter_travelrequest_trip_delete_travelplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytrip',
            name='status',
            field=models.CharField(blank=True, choices=[('planning', 'planning'), ('completed', 'completed'), ('canceled', 'canceled'), ('pending', 'pending')], default='planning', max_length=11, null=True),
        ),
    ]
