# Generated by Django 4.2.5 on 2023-11-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_alter_mytrip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytrip',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('dating', 'dating'), ('family', 'family')], max_length=7, null=True),
        ),
    ]
