# Generated by Django 4.2.5 on 2023-11-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_mytrip_looking_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytrip',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
