# Generated by Django 4.2.5 on 2023-12-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_mytrip_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytrip',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
