# Generated by Django 4.2.5 on 2023-12-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_alter_travelrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytrip',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('dating', 'dating'), ('family', 'family')], max_length=15, null=True),
        ),
    ]
