# Generated by Django 4.2.5 on 2024-06-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_alter_mytrip_looking_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytrip',
            name='looking_for',
            field=models.CharField(choices=[('dating', 'dating'), ('family', 'family')], default='dating', max_length=15),
        ),
    ]
