# Generated by Django 4.2.5 on 2025-07-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_alter_mytrip_looking_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytrip',
            old_name='travel_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='mytrip',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
