# Generated by Django 4.2.5 on 2023-09-28 18:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=accounts.models.user_cover_photo_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_profiles', to='accounts.coverphoto'),
        ),
    ]
