# Generated by Django 4.2.5 on 2023-09-28 18:42

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='coverphoto',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_photos', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='coverphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_cover_photo_upload_path),
        ),
    ]
