# Generated by Django 4.2.5 on 2023-10-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_drink_choice_data_migration'),
        ('accounts', '0016_FamilyPlanChoice_data_migrations'),
        ('accounts', '0017_WorkoutPlanChoice_data_migrations'),
    ]

    operations = [
    ]
