# Generated by Django 4.2.5 on 2023-10-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_profilepreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='orientation',
            field=models.CharField(blank=True, choices=[('Hetero', 'Heterosexual'), ('Homo', 'Homo'), ('Pan', 'Pansexual'), ('Bi', 'Bisexual')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('TM', 'Transgender Male'), ('TF', 'Transgender Female')], max_length=2, null=True),
        ),
    ]
