# Generated by Django 4.2.5 on 2023-10-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_user_login_otp_user_login_otp_validity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shared_secret',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
