# Generated by Django 4.2.5 on 2023-10-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_user_shared_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login_verfication_status',
            new_name='has_2fa_enabled',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='two_step_verification',
            new_name='has_2fa_passed',
        ),
    ]
