# Generated by Django 4.2.5 on 2023-12-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_user_sponsor_user_sponsor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sponsor_name',
        ),
    ]
