# Generated by Django 4.2.5 on 2023-12-06 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_user_mlm_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mlm_choice',
            new_name='mlm_status',
        ),
    ]
