# Generated by Django 4.2.5 on 2023-12-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_alter_package_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', models.TextField()),
                ('terms_and_conditions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('company_mail', models.EmailField(blank=True, max_length=100)),
                ('email_host', models.CharField(blank=True, max_length=100)),
                ('email_port', models.IntegerField(default=587)),
                ('email_host_user', models.EmailField(blank=True, max_length=100)),
                ('email_host_password', models.CharField(blank=True, max_length=100)),
                ('email_tls', models.BooleanField(default=True)),
                ('paypal_client_id', models.CharField(blank=True, max_length=500)),
                ('paypal_client_secret', models.CharField(blank=True, max_length=500)),
                ('paypal_base_url', models.CharField(blank=True, max_length=100)),
                ('welcome_mail', models.BooleanField(default=True)),
                ('company_address', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
