# Generated by Django 4.2.5 on 2023-11-16 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_usertestimonial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='connected',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='roomchat',
            name='receiver_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='roomchat',
            name='sender_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.userprofile'),
        ),
    ]
