# Generated by Django 4.2.5 on 2023-11-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_receiver_alter_chat_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomchat',
            old_name='receiver_profile',
            new_name='receiverProfile',
        ),
        migrations.RenameField(
            model_name='roomchat',
            old_name='sender_profile',
            new_name='senderProfile',
        ),
    ]
