# Generated by Django 4.2.5 on 2023-12-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_sticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchat',
            name='encryption_key',
            field=models.BinaryField(null=True),
        ),
    ]
