# Generated by Django 4.2.5 on 2025-06-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_roomchat_encryption_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.CharField(default='text', max_length=25, null=True),
        ),
    ]
