# Generated by Django 4.2.5 on 2023-09-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_coverphoto_remove_userprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='accounts.coverphoto'),
        ),
    ]
