# Generated by Django 4.2.5 on 2023-09-28 19:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_coverphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_cover_photo_upload_path),
        ),
    ]
