# Generated by Django 4.2.5 on 2023-10-05 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20231005_0715'),
        ('accounts', '019_WorkoutChoice_data_migrations'),
        ('accounts', '020_RelationShipGoals_Data_migrations'),
        ('accounts', '021_SmokeChoices_Data_Migrations'),
        ('accounts', '022_EducationTypes_Data_Migrations'),
    ]

    operations = [
    ]
