# Generated by Django 4.2.5 on 2023-10-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_merge_20231005_0947'),
        ('accounts', '0024_Interests_Data_Migrations'),
    ]

    operations = [
    ]
