# Generated by Django 4.2.5 on 2023-10-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_user_auth_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_choices', models.ManyToManyField(blank=True, related_name='profile_preferences_drink', to='accounts.drinkchoice')),
                ('education_choices', models.ManyToManyField(blank=True, related_name='profile_preferences_education', to='accounts.educationtype')),
                ('family_choices', models.ManyToManyField(blank=True, related_name='profile_preferences_family', to='accounts.familyplanchoice')),
                ('languages_choices', models.ManyToManyField(blank=True, related_name='profile_preferences_languages', to='accounts.language')),
                ('relationship_choices', models.ManyToManyField(blank=True, related_name='profile_preferences_relationship', to='accounts.relationshipgoal')),
                ('religion_choices', models.ManyToManyField(blank=True, related_name='profile_preferences_religion', to='accounts.religion')),
                ('smoke_choices', models.ManyToManyField(blank=True, related_name='profile_preferences_smoke', to='accounts.smokechoice')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('workout_choices', models.ManyToManyField(blank=True, related_name='profile_preferences_workout', to='accounts.workout')),
            ],
        ),
    ]
