# Generated by Django 4.2.5 on 2023-10-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_rename_login_verfication_status_user_has_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp',
            new_name='register_otp',
        ),
    ]
