# Generated by Django 4.2.5 on 2023-10-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_rename_otp_user_register_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shared_secret',
        ),
    ]
