# Generated by Django 4.2.5 on 2023-10-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='height',
            new_name='feet',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inches',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drink_choice', to='accounts.drinkchoice'),
        ),
    ]
