# Generated by Django 4.2.5 on 2023-10-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_rename_height_userprofile_feet_userprofile_inches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
