# Generated by Django 4.2.5 on 2023-10-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_userprofile_height_cm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='feet',
            new_name='height',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='inches',
        ),
    ]
