# Generated by Django 4.2.5 on 2023-10-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_userprofile_state_userprofile_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='showAge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='showDistance',
            field=models.BooleanField(default=False),
        ),
    ]
