# Generated by Django 4.2.5 on 2023-11-11 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_userprofile_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('status', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_testimonial', to='accounts.userprofile')),
            ],
        ),
    ]
