# Generated by Django 4.2.5 on 2023-11-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_package_user_package_validity_order_user_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
