# Generated by Django 4.2.5 on 2023-11-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=10, null=True),
        ),
    ]
