# Generated by Django 4.2.5 on 2023-12-01 04:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_img',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.package_upload_path),
        ),
    ]
