# Generated by Django 4.2.5 on 2023-12-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Initiated'), (1, 'Success'), (2, 'Failed')], default=0),
        ),
    ]
