# Generated by Django 4.2.5 on 2023-12-05 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_EmailContent_Data_Migrations'),
    ]

    operations = [

        migrations.AddField(
            model_name='user',
            name='sponsor_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
