# Generated by Django 4.2.5 on 2023-12-05 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_EmailContent_Data_Migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
