# Generated by Django 4.2.5 on 2023-12-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_remove_user_sponsor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mlm_choice',
            field=models.CharField(blank=True, choices=[('inactive', 'inactive'), ('active', 'active')], max_length=8, null=True),
        ),
    ]
