# Generated by Django 4.2.5 on 2023-12-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_alter_user_mlm_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='showAge',
            field=models.BooleanField(default=True),
        ),
    ]
