# Generated by Django 4.2.5 on 2023-12-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_alter_user_showage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(blank=True, choices=[('register', 'register'), ('otp', 'otp'), ('reset_password', 'reset_password')], max_length=25, null=True),
        ),
    ]
