# Generated by Django 4.2.5 on 2023-12-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_alter_emailtemplate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
