# Generated by Django 4.2.5 on 2023-12-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_package_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.JSONField(null=True),
        ),
    ]
