# Generated by Django 4.2.5 on 2023-12-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_Configurations_Migrations'),
        ('accounts', '0076_Package_Data_Migrations'),
    ]

    operations = [
    ]
