# Generated by Django 4.2.5 on 2023-12-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_merge_20231216_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepreference',
            name='maximum_age',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilepreference',
            name='minimum_age',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
