# Generated by Django 4.2.5 on 2023-12-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_profilepreference_maximum_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepreference',
            name='maximum_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepreference',
            name='minimum_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
