# Generated by Django 4.2.5 on 2023-12-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_alter_profilepreference_maximum_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orientation',
            field=models.CharField(blank=True, choices=[('Hetero', 'Heterosexual'), ('Homo', 'Homo'), ('Bi', 'Bisexual')], max_length=7, null=True),
        ),
    ]
