# Generated by Django 4.2.5 on 2023-12-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_alter_user_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mlm_status',
            field=models.CharField(blank=True, choices=[('inactive', 'inactive'), ('upgraded', 'upgraded'), ('active', 'active')], default='inactive', max_length=8, null=True),
        ),
    ]
