# Generated by Django 4.2.5 on 2024-06-26 05:35

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_alter_user_mlm_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='company_logo',
            field=models.ImageField(blank=True, default=accounts.models.default_company_logo, null=True, upload_to=accounts.models.company_upload_path),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='privacy_policy',
            field=models.TextField(default='privacy policy dummy content'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='terms_and_conditions',
            field=models.TextField(default='terms and conditions dummy content'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sponsor_username',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='MlmApiHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Initiated'), (1, 'Success'), (2, 'Failed')], default=0)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
