# Generated by Django 4.2.5 on 2023-12-20 05:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_alter_user_mlm_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.company_upload_path),
        ),
    ]
