# Generated by Django 4.2.5 on 2024-06-27 11:28

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_alter_companydata_company_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(blank=True, choices=[('en', 'en'), ('zh', 'zh'), ('es', 'es'), ('ru', 'ru')], max_length=2, null=True)),
                ('site_language', models.CharField(blank=True, max_length=50, null=True)),
                ('package_img', models.ImageField(blank=True, null=True, upload_to=accounts.models.site_language_upload_path)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='site_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.sitelanguage'),
        ),
    ]
