# Generated by Django 4.2.5 on 2024-06-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_alter_companydata_company_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_language', models.CharField(blank=True, choices=[('en', 'en'), ('zh', 'zh'), ('es', 'es'), ('ru', 'ru')], max_length=2, null=True)),
            ],
        ),
    ]
