# Generated by Django 4.2.5 on 2024-06-27 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_sitelanguage_Migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.sitelanguage'),
        ),
    ]
