# Generated by Django 4.2.5 on 2025-05-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_SiteLanguage_Data_Migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='showDistance',
            field=models.BooleanField(default=True),
        ),
    ]
