# Generated by Django 4.2.5 on 2025-05-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_alter_user_showdistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='paypal_product_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
