# Generated by Django 4.2.5 on 2025-10-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_alter_user_showdistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_2fa_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
