version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'dating_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'usPasswrd'
      MYSQL_ROOT_PASSWORD: 'rooPasswrd'
    ports:
      - '8007:3306'
    volumes:
      - ./database:/var/lib/mysql

  dating-backend:
      image: django_dev:0.1
      ports:
          - 8019:8019
      volumes:
          - ./djangorest:/home/app/webapp
      command: uvicorn djangorest.asgi:application --host 0.0.0.0 --port 8019
      
      # command: daphne -u myproject.asgi:application
      
      depends_on:
        - db

  
  # phpmyadmin:
  #     image: phpmyadmin:latest
  #     ports:
  #         - "7005:80"
  #     depends_on:
  #         - db
  #     environment:
  #         - PMA_HOST=db
  #         # - PMA_ARBITRARY=1
