# Generated by Django 4.2.5 on 2023-10-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_userprofile_about_me_userprofile_latitude_and_more'),
        ('followers', '0004_blockeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poked_by', to='accounts.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poke', to='accounts.userprofile')),
            ],
        ),
    ]
