# Generated by Django 4.2.5 on 2023-10-28 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_userprofile_about_me_userprofile_latitude_and_more'),
        ('followers', '0005_poke'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_count', models.PositiveIntegerField(default=0)),
                ('cover_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_photo', to='accounts.coverphoto')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_by', to='accounts.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_user', to='accounts.userprofile')),
            ],
        ),
    ]
