# Generated by Django 4.2.5 on 2023-12-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0006_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeduser',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='report_status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected'), (3, 'Blocked')], default=3),
        ),
    ]
