# Generated by Django 4.2.5 on 2023-12-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0007_blockeduser_description_blockeduser_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeduser',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
